// Real trip itinerary — Switzerland & Italy, May–June 2026

const itinerary = [
  // ──── Day 0: Travel ────
  {
    id: "may17-depart",
    date: "2026-05-17",
    dayLabel: "Travel Day",
    title: "Depart Atlanta",
    location: "Atlanta, GA",
    lat: 33.6407,
    lon: -84.4277,
    startTime: "22:30",
    endTime: "23:59",
    description: "Overnight flight to London (BA 226). The adventure begins!",
    category: "travel",
    emoji: "✈️",
    image: "atlanta"
  },

  // ──── Day 1: Arrival → Montreux ────
  {
    id: "may18-arrive-london",
    date: "2026-05-18",
    dayLabel: "Arrival → Montreux",
    title: "Land in London",
    location: "London Heathrow, UK",
    lat: 51.4700,
    lon: -0.4543,
    startTime: "11:45",
    endTime: "14:10",
    description: "Arrive at Heathrow. Quick layover before the flight to Geneva.",
    category: "travel",
    emoji: "✈️",
    image: "london"
  },
  {
    id: "may18-fly-geneva",
    date: "2026-05-18",
    dayLabel: "Arrival → Montreux",
    title: "Fly to Geneva",
    location: "Geneva, Switzerland",
    lat: 46.2044,
    lon: 6.1432,
    startTime: "14:10",
    endTime: "16:55",
    description: "BA 750 to Geneva. Pick up rental car at the airport (5:30–6:30 PM), then drive ~1 hour to Montreux.",
    category: "travel",
    emoji: "✈️",
    image: "geneva"
  },
  {
    id: "may18-montreux-evening",
    date: "2026-05-18",
    dayLabel: "Arrival → Montreux",
    title: "Evening in Montreux",
    location: "Montreux, Switzerland",
    lat: 46.4312,
    lon: 6.9107,
    startTime: "18:30",
    endTime: "21:00",
    description: "Check in at Rue du Sacre du Printemps 12. Walk along the Lake Geneva promenade — flat and stroller-friendly. Dinner nearby and early night after the long journey.",
    category: "sightseeing",
    emoji: "🌅",
    image: "montreux"
  },

  // ──── Day 2: Montreux (easy day) ────
  {
    id: "may19-chillon",
    date: "2026-05-19",
    dayLabel: "Montreux (Easy Day)",
    title: "Château de Chillon",
    location: "Montreux, Switzerland",
    lat: 46.4142,
    lon: 6.9275,
    startTime: "09:30",
    endTime: "11:30",
    description: "Visit the stunning medieval castle on Lake Geneva. 5 min drive with easy parking. Very kid-friendly — towers to climb, tunnels to explore, and open courtyards.",
    category: "sightseeing",
    emoji: "🏰",
    image: "chillon"
  },
  {
    id: "may19-lake-lunch",
    date: "2026-05-19",
    dayLabel: "Montreux (Easy Day)",
    title: "Lunch & Lake Promenade",
    location: "Montreux, Switzerland",
    lat: 46.4312,
    lon: 6.9107,
    startTime: "12:00",
    endTime: "14:00",
    description: "Lunch at a lakeside restaurant. Stroller nap walk along the flower-lined lake promenade with views of the Alps.",
    category: "food",
    emoji: "🍽️",
    image: "lakeside"
  },
  {
    id: "may19-rochers",
    date: "2026-05-19",
    dayLabel: "Montreux (Easy Day)",
    title: "Rochers-de-Naye",
    location: "Montreux, Switzerland",
    lat: 46.4312,
    lon: 6.9780,
    startTime: "14:30",
    endTime: "16:30",
    description: "Optional: scenic cogwheel train ride to the summit at 2,042m. Panoramic views over Lake Geneva and the Alps, plus Alpine marmots!",
    category: "sightseeing",
    emoji: "🏔️",
    optional: true,
    image: "rochers"
  },

  // ──── Day 3: Drive → Lauterbrunnen 🎂 ────
  {
    id: "may20-drive",
    date: "2026-05-20",
    dayLabel: "Drive to Lauterbrunnen 🎂",
    title: "Scenic Drive to Lauterbrunnen",
    location: "Lauterbrunnen, Switzerland",
    lat: 46.5936,
    lon: 7.9091,
    startTime: "11:00",
    endTime: "13:30",
    description: "Check out by 11 AM. Scenic 2 hr 15 min drive through the Swiss countryside with flexible stops. Lunch upon arrival.",
    category: "travel",
    emoji: "🚗",
    image: "lauterbrunnen"
  },
  {
    id: "may20-rest",
    date: "2026-05-20",
    dayLabel: "Drive to Lauterbrunnen 🎂",
    title: "Rest & Settle In",
    location: "Lauterbrunnen, Switzerland",
    lat: 46.5936,
    lon: 7.9091,
    startTime: "13:30",
    endTime: "16:00",
    description: "Nap time and rest at the Airbnb (Luterbach 208G). Check-in at 4 PM. Recharge for the evening.",
    category: "rest",
    emoji: "😴",
    image: "lbvalley"
  },
  {
    id: "may20-staubbach",
    date: "2026-05-20",
    dayLabel: "Drive to Lauterbrunnen 🎂",
    title: "Staubbach Falls",
    location: "Lauterbrunnen, Switzerland",
    lat: 46.5936,
    lon: 7.9091,
    startTime: "16:30",
    endTime: "17:30",
    description: "Short, flat walk to the iconic 297m Staubbach Falls — one of the highest free-falling waterfalls in Europe. Visible right from the village!",
    category: "sightseeing",
    emoji: "💦",
    image: "staubbach"
  },
  {
    id: "may20-birthday",
    date: "2026-05-20",
    dayLabel: "Drive to Lauterbrunnen 🎂",
    title: "Birthday Dinner 🎉",
    location: "Lauterbrunnen, Switzerland",
    lat: 46.5936,
    lon: 7.9091,
    startTime: "18:30",
    endTime: "21:00",
    description: "Celebrate with a birthday dinner in the valley! Optional: catch the sunset from Mürren if energy allows.",
    category: "food",
    emoji: "🎂",
    image: "birthday"
  },

  // ──── Day 4: Mürren ────
  {
    id: "may21-murren",
    date: "2026-05-21",
    dayLabel: "Mürren",
    title: "Explore Mürren",
    location: "Mürren, Switzerland",
    lat: 46.5590,
    lon: 7.8925,
    startTime: "09:00",
    endTime: "12:30",
    description: "Park once and take the cable car up to Mürren — a car-free Alpine village perched on a cliff. Safe streets, playgrounds, easy walks, and jaw-dropping views of the Eiger, Mönch, and Jungfrau.",
    category: "sightseeing",
    emoji: "🚡",
    image: "murren"
  },
  {
    id: "may21-afternoon",
    date: "2026-05-21",
    dayLabel: "Mürren",
    title: "Valley Afternoon",
    location: "Lauterbrunnen, Switzerland",
    lat: 46.5936,
    lon: 7.9091,
    startTime: "13:00",
    endTime: "18:00",
    description: "Stroller nap or return to the Airbnb. Relax in the Lauterbrunnen valley — explore the village, play by the river, or simply enjoy the views.",
    category: "rest",
    emoji: "🌿",
    image: "lbvalley"
  },

  // ──── Day 5: Wengen ────
  {
    id: "may22-wengen",
    date: "2026-05-22",
    dayLabel: "Wengen",
    title: "Train to Wengen",
    location: "Wengen, Switzerland",
    lat: 46.6053,
    lon: 7.9222,
    startTime: "09:00",
    endTime: "12:30",
    description: "Take the train up to this car-free village — great for kids with wide paths and stunning mountain views. Explore the village and enjoy the peaceful Alpine atmosphere.",
    category: "sightseeing",
    emoji: "🚂",
    image: "wengen"
  },
  {
    id: "may22-afternoon",
    date: "2026-05-22",
    dayLabel: "Wengen",
    title: "Afternoon Rest & Café",
    location: "Lauterbrunnen, Switzerland",
    lat: 46.5936,
    lon: 7.9091,
    startTime: "13:00",
    endTime: "18:00",
    description: "Nap time, then a relaxed afternoon at a café. Low-key evening in the valley.",
    category: "rest",
    emoji: "☕",
    image: "wengencafe"
  },

  // ──── Day 6: Flexible ────
  {
    id: "may23-option-a",
    date: "2026-05-23",
    dayLabel: "Flexible Day",
    title: "Option A: Jungfraujoch",
    location: "Jungfraujoch, Switzerland",
    lat: 46.5472,
    lon: 7.9853,
    startTime: "08:00",
    endTime: "16:00",
    description: "The epic option — train to the Top of Europe at 3,454m. Long day but unforgettable: Ice Palace, Sphinx Observatory, panoramic Alpine views. Book tickets in advance.",
    category: "sightseeing",
    emoji: "🏔️",
    optional: true,
    image: "jungfraujoch"
  },
  {
    id: "may23-option-b",
    date: "2026-05-23",
    dayLabel: "Flexible Day",
    title: "Option B: Trümmelbach Falls",
    location: "Lauterbrunnen, Switzerland",
    lat: 46.5693,
    lon: 7.9111,
    startTime: "09:00",
    endTime: "12:00",
    description: "The easy option — just a 10 min drive. Incredible waterfalls inside the mountain, carved by glacial meltwater from the Eiger. Accessible by elevator and walkways.",
    category: "sightseeing",
    emoji: "💦",
    optional: true,
    image: "trummelbach"
  },

  // ──── Day 7: Drive → Locarno ────
  {
    id: "may24-drive-locarno",
    date: "2026-05-24",
    dayLabel: "Drive to Locarno",
    title: "Scenic Drive to Locarno",
    location: "Locarno, Switzerland",
    lat: 46.1708,
    lon: 8.7994,
    startTime: "10:00",
    endTime: "13:00",
    description: "Check out by 10 AM. Beautiful 3-hour drive south through the Alps to the Italian-speaking Ticino region. Nap-friendly route!",
    category: "travel",
    emoji: "🚗",
    image: "locarno"
  },
  {
    id: "may24-piazza",
    date: "2026-05-24",
    dayLabel: "Drive to Locarno",
    title: "Piazza Grande & Gelato",
    location: "Locarno, Switzerland",
    lat: 46.1708,
    lon: 8.7994,
    startTime: "17:00",
    endTime: "21:00",
    description: "Check in at Via Bartolomeo Rusca 9 after 3 PM. Evening at Piazza Grande — the big open square is perfect for kids to run around. Dinner and gelato with a Mediterranean vibe.",
    category: "food",
    emoji: "🍦",
    image: "locarnorest"
  },

  // ──── Day 8: Valle Verzasca ────
  {
    id: "may25-verzasca",
    date: "2026-05-25",
    dayLabel: "Valle Verzasca",
    title: "Valle Verzasca",
    location: "Valle Verzasca, Switzerland",
    lat: 46.2572,
    lon: 8.8444,
    startTime: "09:00",
    endTime: "13:00",
    description: "25 min drive to one of Switzerland's hidden gems. Turquoise-green river, the famous Ponte dei Salti stone bridge, and shallow spots perfect for supervised kids' play.",
    category: "sightseeing",
    emoji: "🏞️",
    image: "verzasca"
  },
  {
    id: "may25-afternoon",
    date: "2026-05-25",
    dayLabel: "Valle Verzasca",
    title: "Afternoon Rest & Dinner",
    location: "Locarno, Switzerland",
    lat: 46.1708,
    lon: 8.7994,
    startTime: "13:00",
    endTime: "20:00",
    description: "Nap in the car or back at the Airbnb. Evening dinner in Locarno.",
    category: "rest",
    emoji: "😴",
    image: "locarno"
  },

  // ──── Day 9: Travel → Florence ────
  {
    id: "may26-travel-florence",
    date: "2026-05-26",
    dayLabel: "Travel to Florence",
    title: "Return Car & Train to Florence",
    location: "Florence, Italy",
    lat: 43.7696,
    lon: 11.2558,
    startTime: "09:00",
    endTime: "15:00",
    description: "Return the rental car in the morning. Train to Florence — sit back and watch the scenery shift from Alpine to Tuscan.",
    category: "travel",
    emoji: "🚂",
    image: "florence"
  },
  {
    id: "may26-ponte-vecchio",
    date: "2026-05-26",
    dayLabel: "Travel to Florence",
    title: "Ponte Vecchio & Dinner",
    location: "Florence, Italy",
    lat: 43.7680,
    lon: 11.2531,
    startTime: "17:00",
    endTime: "21:00",
    description: "Check in at Borgo Santi Apostoli 13 after 3 PM. Walk to the iconic Ponte Vecchio — just 5 minutes away. Evening stroll, dinner, and gelato in the golden Florentine light.",
    category: "sightseeing",
    emoji: "🌉",
    image: "pontevecchio"
  },

  // ──── Day 10: Florence ────
  {
    id: "may27-boboli",
    date: "2026-05-27",
    dayLabel: "Florence",
    title: "Boboli Gardens",
    location: "Florence, Italy",
    lat: 43.7626,
    lon: 11.2480,
    startTime: "09:00",
    endTime: "12:00",
    description: "Morning exploring the Renaissance Boboli Gardens — space to run, shady paths, fountains, grottos, and panoramic views over Florence. Perfect for little ones.",
    category: "sightseeing",
    emoji: "🌳",
    image: "boboli"
  },
  {
    id: "may27-signoria",
    date: "2026-05-27",
    dayLabel: "Florence",
    title: "Piazza della Signoria",
    location: "Florence, Italy",
    lat: 43.7696,
    lon: 11.2558,
    startTime: "15:00",
    endTime: "17:00",
    description: "After lunch and nap, explore the open-air sculpture gallery. The lively piazza, Neptune Fountain, and replica David make this Florence's living room.",
    category: "sightseeing",
    emoji: "🗿",
    image: "signoria"
  },
  {
    id: "may27-michelangelo",
    date: "2026-05-27",
    dayLabel: "Florence",
    title: "Piazzale Michelangelo Sunset",
    location: "Florence, Italy",
    lat: 43.7629,
    lon: 11.2650,
    startTime: "19:00",
    endTime: "21:30",
    description: "Optional adults' evening: climb or taxi to Piazzale Michelangelo for the best sunset panorama in Florence — the Duomo, river, and hills all laid out below. Dinner with a view.",
    category: "sightseeing",
    emoji: "🌇",
    optional: true,
    image: "michelangelo"
  },

  // ──── Day 11: Wedding transfer ────
  {
    id: "may28-wedding",
    date: "2026-05-28",
    dayLabel: "Wedding Transfer",
    title: "Head to Villa Boscarello",
    location: "Villa Boscarello, Italy",
    lat: 43.3500,
    lon: 11.5500,
    startTime: "10:00",
    endTime: "14:00",
    description: "Check out by 10 AM. Travel to Villa Boscarello for the wedding celebrations. Enjoy the Tuscan countryside!",
    category: "travel",
    emoji: "💒",
    image: "tuscany"
  },

  // ──── Day 16: Travel Home ────
  {
    id: "jun02-depart",
    date: "2026-06-02",
    dayLabel: "Travel Home",
    title: "Fly Home via Paris",
    location: "Florence → Paris → Atlanta",
    lat: 43.7696,
    lon: 11.2558,
    startTime: "13:05",
    endTime: "19:50",
    description: "1:05 PM Florence → Paris (AF 1467). 4:25 PM Paris → Atlanta (AF 34). Arrive ATL at 7:50 PM. Welcome home!",
    category: "travel",
    emoji: "✈️",
    image: "flight"
  }
];

module.exports = itinerary;
